### PR TITLE
Feature 2 is developed, please review 

### PR DESCRIPTION
**Pull request by devarachandrasekhar**
Feature 2 is developed, please review

### CODE REVIEW

**Comment by Chandu154** [comment]
check once again

**Comment by devarachandrasekhar** [comment]
> check once again

checked once again ,it seems good

**Comment by Chandu154** [comment]
few code is missing and add appropriately

**Comment by devarachandrasekhar** [comment]
added the missing code

**Review by Chandu154 — APPROVED** [review]
everting good

**Review by devarachandrasekhar — COMMENTED** [review]
good

**Pull request merged**
